name:                distributive-try
version:             0.1.0.0
github:              "gregorias/distributive-try"
license:             AGPL-3
author:              "Grzegorz Milka"
maintainer:          "grzegorzmilka@gmail.com"
copyright:           "Copyright (c) 2020 Grzegorz Milka"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gregorias/distributive-try#readme>

# Defaults recommended by https://kowainik.github.io/posts/2019-02-06-style-guide#default-extensions
# Also use Relude
default-extensions:
  DerivingStrategies
  GeneralisedNewtypeDeriving
  InstanceSigs
  LambdaCase
  NoImplicitPrelude
  NumericUnderscores
  ScopedTypeVariables
  TupleSections
  TypeApplications
  UnicodeSyntax

dependencies:
- base >= 4.13 && < 5

library:
  source-dirs: src
  dependencies:
  - megaparsec
  - relude

tests:
  distributive-try-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Spec
    dependencies:
    - distributive-try
    - hspec
    - megaparsec
    - relude
